version: '3.7'

services:

  routeros-6-46:
    image: evilfreelancer/docker-routeros:6.46.5
    cap_add:
        - NET_ADMIN
    devices:
        - /dev/net/tun
    ports:
        - "22222:22"
        - "22223:23"
        - "28728:8728"
        - "28729:8729"
        - "8080:80"
        - "8292:8292"
    networks:
      profiler_net:
        ipv4_address: 172.42.1.6
      
  influxdb:
    build:
        context: ./influxdb
        dockerfile: dockerfile
    ports:
        - 8086:8086
    env_file:
        - influx-variables.env
    #environment:
    #    - INFLUX_USER=$INFLUX_USER
    #    - INFLUX_BUCKET_NAME=$INFLUX_BUCKET_NAME
    #    - INFLUX_PSW=$INFLUX_PSW
    #    - INFLUX_TOKEN=$INFLUX_TOKEN
    #    - INFLUX_RETENTION_TIME=$INFLUX_RETENTION_TIME
    #    - INFLUX_ORG=$INFLUX_ORG
    networks:
      profiler_net:
        ipv4_address: 172.42.1.8
  
networks:
  profiler_net:
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/16
    attachable: true
